### ISSUE TITLE
 when i run the web application i get this error

### ISSUE THREAD

**Issue by AndriiReverchuk** [tarique-khan/configurable_expansion_tile#1]
/C:/tools/flutter_windows_2.5.3-stable/flutter/.pub-cache/hosted/pub.dartlang.org/advance_expansion_tile-1.0.1/lib/advance_expansion_tile.dart:5:8: Error: Not found: 'dart:ffi'

[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19043.1889], locale uk-UA)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.5)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.71.0)
[√] Connected device (3 available)
[√] HTTP Host Availability

**Comment by eggzotic** [comment]
ditto. The very first thing that has just happened to me. Perhaps the "web" tag needs to be dropped from this package?

richard@Richards-MacBook-Pro gui % flutter run -d chrome
Launching lib/main.dart on Chrome in debug mode...
../../../.pub-cache/hosted/pub.dartlang.org/advance_expansion_tile-1.0.1/lib/advance_expansion_tile.dart:5:8: Error: Not found: 'dart:ffi'
import 'dart:ffi';
       ^
Waiting for connection from debug service on Chrome...             13.0s
Failed to compile application.
richard@Richards-MacBook-Pro gui % 
richard@Richards-MacBook-Pro gui % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.5.0-6.0.pre.29, on macOS 12.6 21G115 darwin-arm64, locale en-NZ)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.73.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by AndriiReverchuk** [comment]
I removed this import, it worked for me.
True, now the package is stored in the project, but this is not critical.

**Comment by tarique-khan** [comment]
[AndriiReverchuk](https://github.com/AndriiReverchuk), [eggzotic](https://github.com/eggzotic) the issue if fixed and the library is updated on the pub.dev

**Comment by eggzotic** [comment]
Fantastic - thx!

FYI, I found that with the builtin ExpansionPanel and ExpansionPanelList, we can achieve the specific functionality I was looking for - external control of the individual expand/collapse state - so I am pretty happy with that. Example/demo at https://github.com/eggzotic/expansion_panel_demo
